#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : oslosphinx
Version  : 4.12.0
Release  : 33
URL      : https://tarballs.openstack.org/oslosphinx/oslosphinx-4.12.0.tar.gz
Source0  : https://tarballs.openstack.org/oslosphinx/oslosphinx-4.12.0.tar.gz
Source99 : https://tarballs.openstack.org/oslosphinx/oslosphinx-4.12.0.tar.gz.asc
Summary  : OpenStack Sphinx Extensions and Theme
Group    : Development/Tools
License  : Apache-2.0
Requires: oslosphinx-python
Requires: pbr
Requires: requests
Requires: six
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/oslosphinx.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package python
Summary: python components for the oslosphinx package.
Group: Default

%description python
python components for the oslosphinx package.


%prep
%setup -q -n oslosphinx-4.12.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1492457640
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1492457640
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
